-- ==========================================
-- Synthetix Database Schema for Supabase
-- ==========================================

-- 1. Create a Public Users Table
-- Supabase automatically manages auth.users, but it's best practice to keep a 
-- public.users table for application-level data and foreign keys.
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the Documents Table
CREATE TABLE public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    raw_content TEXT NOT NULL
);

-- 3. Create the Syntheses Table
CREATE TABLE public.syntheses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    query TEXT,                  -- Optional user question
    query_answer TEXT,           -- AI generated answer
    summary JSONB,               -- Array of strings (Flashcards)
    quiz JSONB,                  -- Array of MCQ objects
    knowledge_graph JSONB        -- Nodes and edges for React Flow
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.syntheses ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies
-- Users can only see, create, and edit their OWN records
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.users FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can view own documents" ON public.documents FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow backend insert documents" ON public.documents FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can delete own documents" ON public.documents FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own syntheses" ON public.syntheses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow backend insert syntheses" ON public.syntheses FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can delete own syntheses" ON public.syntheses FOR DELETE USING (auth.uid() = user_id);

-- Optional: Supabase Trigger to auto-create public.users when auth.users is created
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
